export default {
    products: [
    {
        _id: '1',
        name: 'Slim Shirt',
        category: 'Shirts',
        image: '/images/p1.jpg',
        price: 60,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
    },
    {
        _id: '2',
        name: 'Fit Shirt',
        category: 'Shirts',
        image: '/images/p2.jpg',
        price: 80,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 45,
        countInStock: 10,
    },
    {
        _id: '3',
        name: 'Loose Shirt',
        category: 'Shirts',
        image: '/images/p3.jpg',
        price: 80,
        brand: 'Nike',
        rating: 4.7,
        numReviews: 30,
        countInStock: 3,
    },
    {
        _id: '4',
        name: 'Slim Pants',
        category: 'Shirts',
        image: '/images/p4.jpg',
        price: 120,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 86,
        countInStock: 6,
    },
    {
        _id: '5',
        name: 'Fit Pants',
        category: 'Pants',
        image: '/images/p5.jpg',
        price: 100,
        brand: 'Nike',
        rating: 4,
        numReviews: 167,
        countInStock: 7,
    },
]
}