export default {
    products: [
    {
        _id: '1',
        name: 'Slim Shirt',
        category: 'Shirts',
        image: '/images/d1.jpg',
        price: 60,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
    },
    {
        _id: '2',
        name: 'Slim Shirt',
        category: 'Shirts',
        image: '/images/d1.jpg',
        price: 60,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        countInStock: 10,
    },
    {
        _id: '3',
        name: 'Fit Shirt',
        category: 'Shirts',
        image: '/images/d1.jpg',
        price: 80,
        brand: 'Nike',
        rating: 4,
        numReviews: 30,
        countInStock: 3,
    },
    {
        _id: '4',
        name: 'Slim Shirt',
        category: 'Shirts',
        image: '/images/d1.jpg',
        price: 60,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
    },
    {
        _id: '5',
        name: 'Slim Shirt',
        category: 'Pants',
        image: '/images/d1.jpg',
        price: 60,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        countInStock: 5,
    },
]
}